# Runs a flake8 analysis on the pull request.
name: PythonLint
on:
    push:
        branches:
            - master
            - dev
    pull_request:
        branches:
            - master
            - dev

jobs:
  Flake8Test:
    # Set up virtual machine
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    
    # Set up environment
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        pip install yapf
        
    # Run linter
    - name: Lint with flake8
      run: flake8 . --count --ignore=E101,W191,E501,F811,F401,W503,F405,E722,F403,E402,F841,W291,F541,E402

    # If needed, format code with yapf formatter
    - name: Format with yapf
      if: failure()
      run: |
        yapf --style "pep8" -pir . -vv
        git config --global user.name github-actions
        git config --global user.email '${GITHUB_ACTOR}@users.noreply.github.com'
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
        git commit -am "fixup! Format Python code with yapf" || true
        git push --force origin HEAD:$GITHUB_REF || true
